In [1]:
import tensorflow as tf

In [27]:
# Build a dataflow graph.
a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
b = tf.constant([[1.0, 1.0], [0.0, 1.0]])
session = tf.InteractiveSession()

In [11]:
r = tf.matmul(a, b)
result = sess.run(e)
print result

[[ 1.  3.]
 [ 3.  7.]]


In [13]:
r = sess.run(tf.add(a,b))
print r

[[ 2.  3.]
 [ 3.  5.]]


In [16]:
r = sess.run(tf.argmax(b,axis=1))
print r

[0 1]


In [17]:
r = sess.run(tf.cast(a, tf.int32))
print r

[[1 2]
 [3 4]]


In [19]:
#Returns element-wise smallest integer in not less than x.
print sess.run(tf.ceil(a))

[[ 1.  2.]
 [ 3.  4.]]


In [29]:
print sess.run(tf.concat([a,b],axis=1)) #1 means zongxiang

[[ 1.  2.  1.  1.]
 [ 3.  4.  0.  1.]]


In [31]:
c = [1,2,3,4]
print sess.run(tf.diag(c))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [33]:
#Inserts a dimension of 1 into a tensor's shape.
print sess.run(tf.expand_dims(c,axis=0))

[[1 2 3 4]]


In [35]:
print sess.run(tf.fill([2, 3], 9))

[[9 9 9]
 [9 9 9]]


In [36]:
print sess.run(tf.ones([2, 3], tf.int32))

[[1 1 1]
 [1 1 1]]


In [ ]:
tf.zeros([3, 4], tf.int32) ==> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [38]:
print sess.run(tf.one_hot(indices = [0, 2, -1, 1],
  depth = 3,
  on_value = 5.0,
  off_value = 0.0,
  axis = -1))

[[ 5.  0.  0.]
 [ 0.  0.  5.]
 [ 0.  0.  0.]
 [ 0.  5.  0.]]


In [ ]:
# 'x' is [[1, 1, 1]
#         [1, 1, 1]]
tf.reduce_sum(x) ==> 6
tf.reduce_sum(x, 0) ==> [2, 2, 2]
tf.reduce_sum(x, 1) ==> [3, 3]
tf.reduce_sum(x, 1, keep_dims=True) ==> [[3], [3]]
tf.reduce_sum(x, [0, 1]) ==> 6

In [ ]:
# 'x' is [[1., 1.]
#         [2., 2.]]
tf.reduce_mean(x) ==> 1.5
tf.reduce_mean(x, 0) ==> [1.5, 1.5]
tf.reduce_mean(x, 1) ==> [1.,  2.]

In [ ]:
# tensor 't' is [1, 2, 3, 4, 5, 6, 7, 8, 9]
# tensor 't' has shape [9]
reshape(t, [3, 3]) ==> [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]

In [ ]:
# 't' is [[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]]
shape(t) ==> [2, 2, 3]

In [ ]:
# 'input' is [[[1, 1, 1], [2, 2, 2]],
#             [[3, 3, 3], [4, 4, 4]],
#             [[5, 5, 5], [6, 6, 6]]]
tf.slice(input, [1, 0, 0], [1, 1, 3]) ==> [[[3, 3, 3]]]
tf.slice(input, [1, 0, 0], [1, 2, 3]) ==> [[[3, 3, 3],
                                            [4, 4, 4]]]
tf.slice(input, [1, 0, 0], [2, 1, 3]) ==> [[[3, 3, 3]],
                                           [[5, 5, 5]]]
slice(
    input_,
    begin,
    size,
    name=None
)

In [ ]:
squeeze(
    input,
    axis=None,
    name=None,
    squeeze_dims=None
)
Removes dimensions of size 1 from the shape of a tensor.
# 't' is a tensor of shape [1, 2, 1, 3, 1, 1],Or, to remove specific size 1 dimensions:
shape(squeeze(t, [2, 4])) ==> [1, 2, 3, 1]
# 't' is a tensor of shape [1, 2, 1, 3, 1, 1]
shape(squeeze(t)) ==> [2, 3]

In [ ]:
stack(
    values,
    axis=0,
    name='stack'
)
Stacks a list of rank-R tensors into one rank-(R+1) tensor.
# 'x' is [1, 4]
# 'y' is [2, 5]
# 'z' is [3, 6]
stack([x, y, z]) => [[1, 4], [2, 5], [3, 6]]  # Pack along first dim.
stack([x, y, z], axis=1) => [[1, 2, 3], [4, 5, 6]]

In [ ]:
unstack(
    value,
    num=None,
    axis=0,
    name='unstack'
)
Unpacks the given dimension of a rank-R tensor into rank-(R-1) tensors.